name: buildExtension
on:
  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
    secrets:
      azureToken:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: downloadArtifact
        id: downloadArtifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ inputs.artifactId }}
          path: out
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: npm install
        uses: jaid/action-npm-install@main
      - id: build
        name: build
        run: npm run buildExtension
      - id: bundle
        name: bundle
        shell: bash
        run: |
          cd
          npm install --no-save --no-package-lock @vscode/vsce
          cd "$GITHUB_WORKSPACE/dist"
          ~/node_modules/.bin/vsce package
          mkdir bundle
          mv *.vsix bundle
      - name: check
        id: check
        shell: bash
        working-directory: ${{ github.workspace }}/dist
        run: |
          ls -l --almost-all --color=always --si --literal --group-directories-first
          ls -l --almost-all --color=always --si --literal --group-directories-first bundle
      - name: upload
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist
          path: ${{ github.workspace }}/dist/bundle/*.vsix
      - name: publish
        id: publish
        shell: bash
        env:
          VSCE_PAT: ${{ secrets.azureToken }}
        run: |-
          ~/node_modules/.bin/vsce publish --allow-star-activation --packagePath ${{ github.workspace }}/dist/bundle/*.vsix
