name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        id: installNodePackages
        working-directory: ${{ runner.workspace }}
        run: npm install --no-save --no-package-lock @actions/core globby read-file-yaml key-counter read-file-json yaml fs-extra tsconfig-jaid lodash-es tsx
      - name: rewriteTsconfigJaid
        id: rewriteTsconfigJaid
        uses: jacobtomlinson/gha-find-replace@3.0.2
        with:
          include: ${{ runner.workspace }}/node_modules/tsconfig-jaid/base.json
          find: '"..'
          replace: '"../..'
          regex: false
      - if: ${{ steps.rewriteTsconfigJaid.outputs.modifiedFiles > 0 }}
        id: build
        name: build
        run: ${{ runner.workspace }}/node_modules/.bin/tsx src/workflows/build/build.ts
      - id: uploadArtifact
        name: uploadArtifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: data
          path: ${{ runner.workspace }}/out
  buildHtml:
    needs: build
    uses: ./.github/workflows/buildHtml.yml
    permissions:
      id-token: write
      pages: write
    with:
      artifactId: data
  # buildExtension:
  #   needs: build
  #   uses: ./.github/workflows/buildExtension.yml
