name: buildExtension
on:
  workflow_call:
    inputs:
      data:
        required: true
        type: string
        description: Data in JSON
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        id: installNodePackages
        working-directory: ${{ runner.workspace }}
        run: npm install --no-save --no-package-lock ts-node @actions/core @actions/github fs-extra globby read-file-yaml prevent-start lodash-es
      - id: build
        name: build
        run: node --loader ts-node/esm .github/workflows/buildExtension.build.ts
      - id: bundle
        name: bundle
        shell: bash
        run: |
          cd
          npm install --no-save --no-package-lock @vscode/vsce
          cd "$GITHUB_WORKSPACE/dist"
          ~/node_modules/.bin/vsce package
          mkdir bundle
          mv *.vsix bundle
      - name: check
        id: check
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE/dist"
          ls -l --almost-all --color=always --si --literal --group-directories-first
          ls -l --almost-all --color=always --si --literal --group-directories-first bundle
      - name: upload
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist
          path: ${{ github.workspace }}/dist/bundle/*.vsix
      - name: publish
        id: publish
        shell: bash
        env:
          VSCE_PAT: ${{ secrets.azureToken }}
        run: |-
          ~/node_modules/.bin/vsce publish --allow-star-activation --packagePath ${{ github.workspace }}/dist/bundle/*.vsix
