name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        id: installNodePackages
        working-directory: ${{ runner.workspace }}
        run: npm install --no-save --no-package-lock ts-node @actions/core @actions/github yaml
      - id: build
        name: build
        working-directory: ${{ github.workspace }}/.github/workflows
        run: node --loader ts-node/esm build.build.ts
