name: buildHtml
on:
  workflow_call:
    inputs:
      data:
        required: true
        type: string
        description: Data in JSON
permissions:
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        id: installNodePackages
        working-directory: ${{ runner.workspace }}
        run: npm install --no-save --no-package-lock ts-node @actions/core @actions/github fs-extra globby read-file-yaml showdown handlebars read-file-string
      - id: build
        name: build
        run: node --loader ts-node/esm .github/workflows/${{ github.workflow }}.build.ts
      - name: check
        id: check
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE/dist"
          ls -l --almost-all --color=always --si --literal --group-directories-first
      - name: Setup Pages
        id: setupPages
        uses: actions/configure-pages@v3.0.6
      - name: uploadPages
        id: uploadPages
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: '${{ github.workspace }}/dist'
      - name: deployPages
        id: deployPages
        uses: actions/deploy-pages@v2.0.4