name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        id: installNodePackages
        working-directory: ${{ runner.workspace }}
        run: npm install --no-save --no-package-lock ts-node @actions/core globby read-file-yaml
      - id: build
        name: build
        run: node --loader ts-node/esm .github/workflows/build.build.ts
    outputs:
      data: ${{ steps.build.outputs.value }}
  buildHtml:
    needs: build
    uses: ./.github/workflows/buildHtml.yml
    with:
      data: ${{ needs.build.outputs.value }}
    permissions:
      id-token: write
      pages: write
  buildExtension:
    needs: build
    uses: ./.github/workflows/buildExtension.yml
    with:
      data: ${{ needs.build.outputs.value }}