name: buildHtml
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
  repository_dispatch:
    types:
      - build
permissions:
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        shell: bash
        run: |
          cd
          npm install --no-save --no-package-lock @actions/core @actions/github fs-extra globby read-file-yaml
      - id: build
        name: build
        shell: bash
        env:
          inputs: ${{ toJSON(inputs) }}
          github: ${{ toJSON(github) }}
        run: node --input-type module < .github/actions/buildHtml/index.js
      - name: check
        id: check
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE/dist"
          ls -l --almost-all --color=always --si --literal --group-directories-first
      # - id: publish
      #   name: publish
      #   uses: peaceiris/actions-gh-pages@v3.9.3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: "$GITHUB_WORKSPACE/dist"
      - name: Setup Pages
        id: setupPages
        uses: actions/configure-pages@v3.0.6
      - name: uploadPages
        id: uploadPages
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: '${{ github.workspace }}/dist'
      - name: deployPages
        id: deployPages
        uses: actions/deploy-pages@v2.0.4