name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        shell: bash
        run: |
          cd
          npm install --no-save --no-package-lock ts-node @actions/core @actions/github yaml
      - id: build
        name: build
        shell: bash
        env:
          inputs: ${{ toJSON(inputs) }}
        # run: node --input-type module --loader ts-node/esm .github/actions/build/index.ts
        run:  ~/node_modules/.bin/ts-node .github/actions/build/index.ts