name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: npm install
        uses: jaid/action-npm-install@main
      - id: build
        name: build
        run: npm run build
      - id: uploadArtifact
        name: uploadArtifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: data
          path: out
  buildHtml:
    needs: build
    uses: ./.github/workflows/buildHtml.yml
    permissions:
      id-token: write
      pages: write
    with:
      artifactId: data
  buildExtension:
    needs: build
    uses: ./.github/workflows/buildExtension.yml
    with:
      artifactId: data
    secrets:
      azureToken: ${{ secrets.azureToken }}