name: buildHtml
on:
  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
permissions:
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: downloadArtifact
        id: downloadArtifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ inputs.artifactId }}
          path: out
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: npm install
        uses: jaid/action-npm-install@main
      - id: build
        name: build
        run: npm run buildHtml
      - name: check
        id: check
        shell: bash
        working-directory: ${{ github.workspace }}/dist
        run: ls -l --almost-all --color=always --si --literal --group-directories-first
      - name: Setup Pages
        id: setupPages
        uses: actions/configure-pages@v3.0.6
      - name: uploadPages
        id: uploadPages
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: '${{ github.workspace }}/dist'
      - name: deployPages
        id: deployPages
        uses: actions/deploy-pages@v2.0.4