name: buildHtml
on:
  workflow_call:
    inputs:
      artifactId:
        required: true
        type: string
permissions:
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: downloadArtifact
        id: downloadArtifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ inputs.artifactId }}
          path: ${{ runner.workspace }}/out
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        id: installNodePackages
        working-directory: ${{ runner.workspace }}
        run: npm install --no-save --no-package-lock ts-node @actions/core @actions/github fs-extra globby read-file-yaml showdown handlebars read-file-string lodash-es tsconfig-paths tsx
      - name: installNodePackagesInRepo
        id: installNodePackagesInRepo
        run: npm install --no-save --no-package-lock tsconfig-jaid
      - id: checkTypescriptConfig
        name: checkTypescriptConfig
        run: |-
          PATH=$PATH:$GITHUB_WORKSPACE/node_modules/.bin:$RUNNER_WORKSPACE/node_modules/.bin
          export PATH
          set -o xtrace
          ls -l --almost-all --color=always --si --literal --group-directories-first $GITHUB_WORKSPACE/node_modules/.bin
          ls -l --almost-all --color=always --si --literal --group-directories-first $RUNNER_WORKSPACE/node_modules/.bin
          tsc --showConfig
      - id: build
        name: build
        run: |-
          PATH=$PATH:$GITHUB_WORKSPACE/node_modules/.bin:$RUNNER_WORKSPACE/node_modules/.bin
          export PATH
          set -o xtrace
          tsx src/workflows/buildHtml/build.ts
      - name: check
        id: check
        shell: bash
        working-directory: ${{ github.workspace }}/dist
        run: ls -l --almost-all --color=always --si --literal --group-directories-first
      - name: Setup Pages
        id: setupPages
        uses: actions/configure-pages@v3.0.6
      - name: uploadPages
        id: uploadPages
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: '${{ github.workspace }}/dist'
      - name: deployPages
        id: deployPages
        uses: actions/deploy-pages@v2.0.4