name: convertGlobals
on:
  workflow_dispatch: {}
jobs:
  convertGlobals:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setupNode
        uses: actions/setup-node@v3.7.0
        with:
          node-version: latest
      - name: installNodePackages
        shell: bash
        run: |
          cd
          npm install --no-save --no-package-lock ts-node @actions/core fs-extra read-file-json yaml key-counter ts-node
      - id: convertGlobals
        name: convertGlobals
        shell: bash
        env:
          inputs: ${{ toJSON(inputs) }}
        run: ts-node .github/actions/convertGlobals/index.ts